### ISSUE TITLE
Failures when deploying to Sandbox

### ISSUE THREAD

**Issue by thoma3mw** [financialforcedev/ffhttp-googlecloudprint#1]
I attempted to deploy this to one of my sandboxes the other day and received these errors.

![ffgcp_failures](https://user-images.githubusercontent.com/7193421/38200891-1ed841de-3664-11e8-8133-b34f77a87fba.png)

It appears that maybe the Core was updated and this code was not updated to match.  Is anyone more familiar with the code able to fix these or tell me how to fix them?

**Comment by kcreech101** [comment]
This is happening for me as well.

**Comment by mwoodcertinia** [comment]
I've updated this repo to take into account the changes in ffhttp-core. You should now be able to deploy without any problems.

Cheers,
Matt
